name: kronym_rpa_unit_worker
description: RPA Worker for Kronym
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.10.3

# Add regular dependencies here.
dependencies:
  path: ^1.9.0
  http: ^1.6.0
  dotenv: ^4.2.0
  json_annotation: ^4.9.0
  puppeteer: ^3.20.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
